### ISSUE TITLE
Add first dose details for those having a second dose

### ISSUE THREAD

**Issue by Richard1793** [DrMikeyS/COVIDVaccinePatientSlips#12]
Hi
Woudl you be able to create a sticker option for second doses that includes the first dose details please?  It'd be useful for those that don't have their card, or for clinics when we did not have cards (the first couple of clinics for us).
Thanks
Richard

**Comment by DrMikeyS** [comment]
Hi Richard, this has already been added. You get three options

1. first dose (where second dose is blank to be handwritten)
2. second dose (where first dose is blank to be handwritten)
3. unassigned dose (where you can circle on the card which dose it is)

In our site, we have used option 3. Patients end up with two cards, but it solves the issue of patients not bringing them back.

There is no way for the system to know when a patient had their first dose sadly.

**Comment by Richard1793** [comment]
There's a workaround:

1. Copy 2nd does clinic list to a spreadsheet
2. Copy vaccinated patients list into a second sheet with name, NHS number, first does vaccine name, batch, date
3. First sheet has a look up for the NHS number to copy the first dose details.  
 
Copying the vaccine type needs an If-Then to insert simple name =IF(IFERROR((FIND("Astra",B5)),0)>0,"Astra",IF(IFERROR((FIND("Pfizer",B5)),0)>0,"Pfizer",""))

**Comment by DrMikeyS** [comment]
Ah gocha, so looking to have a way of then taking the data from the new spreadsheet to the stickers.

I will update the code to add that option. Likely later this week.

**Comment by Richard1793** [comment]
Yup, that's it.  

The change for your code is that the import CSV can have two extra optional columns:
- 1stType (probably need a note to suggest using "Astra Zeneca"  if including Oxford is too long for the label?
- 1stDate

**Comment by Richard1793** [comment]
I've done a quick hack on the source code to add first dose batch numbers on second dose cards.  I'll test it at tomorow's 2nd dose clinic.

Next ->> The same approach gives a workaround for mixed 1st/2nd clinics:
1. Create xls for the clinic that lists patient details and first batch details.  In Sys1 this needs two reports (clinic list and vacc data) that are then merged  in an xls file with lookup formula
2. If first batch/date is empty then the current batch is added as a first.
3. If first batch/date exists then the current batch is added as the second.

Is it best to post the updates here (which could cause confusion) or email Mike to review and incorporate into his official veison?  Or start my own branch?

**Comment by DrMikeyS** [comment]
Hi Richard,
Sorry for the slowness this week, I've been swamped planning for cohorts 10-12. Since you have adapted the code the best thing would be to create a branch and I will review it/test it for you and then pull it into the main version. I'd suggest the github desktop app as a really good way of making new branches easy.
Pop a message on here or submit a pull request for your branch once you have uploaded it.
Thanks for contributing, it is a really useful suggestion.

**Comment by Richard1793** [comment]
Sorry Mike, I've been bamboozled about creating a branch. Do I need permissions to add a branch to your project?

I'll email the files.

**Comment by bunit17** [comment]
Hi Both, 

I missed that Richard had already been working on this. But I have just submitted a pull request with my version of displaying first dose information. 

Matt

**Comment by Richard1793** [comment]
Hi Matt

Thanks, it's sometimes useful to see two different solutions to a problem.  You've implemented the update to all layouts and added age.  

I focussed on enabling mixed 1st & 2nd doses in one clinic.

I've since added a tweak to my version.  When we have a mixed 1st/2nd dose clinic it is useful to draw attention to the second doses.  So I moved the "Second dose" bit of text from being part of the generic section into the block of code that sorts out 1st/2nd doses.  If the pt is on a second dose, I've used capitalised "SECOND DOSE".  I've also highlighted it in yellow.  

I've not uploaded it because I'm not quite sure how github tracks multiple revs overlaying each other.  It's a simple change so I'll note it here for now.

The relevant snippet in function.js is when a second dose is being used:
`line3 = `<span class="semi-bold-highlight">SECOND DOSE: </span> ` + sessiondate + ` at <span class="semi-bold"> ` + sessiontime + `</span>` `

The relevant new CSS is:
`
.semi-bold-highlight {
  font-weight: 500;
background-color: yellow;
}

`

**Comment by DrMikeyS** [comment]
@Richard1793 is there any way we can apply your changes to @bunit17's fork? Your (Richard's) fork has created new files for every change which will mean if I pull it into the main branch it will confuse users. Ideally the changes would be made to the original files and assuming it works in testing we can merge it into the main branch.

**Comment by bunit17** [comment]
@Richard1793 do you want to email me your changes? matthew.burnett @ normal NHS domain. I can then incorporate it into my current fork and issue it as a pull to @DrMikeyS

**Comment by bunit17** [comment]
Hi Both, 

I have now updated my fork with the mixed dose clinic idea from @Richard1793 

Matt

**Comment by Richard1793** [comment]
Thanks Matt.

Out of interest did you look at my coding or just work it out yourself?

**Comment by DrMikeyS** [comment]
@bunit17 I have applied a few updates to your code. Would you mind re-testing and checking that you are happy? Once happy I will pull into the main branch

**Comment by DrMikeyS** [comment]
All implemented
