### ISSUE TITLE
Single QR code option

### ISSUE THREAD

**Issue by DrMikeyS** [DrMikeyS/COVIDVaccinePatientSlips#17]

**Comment by Richard1793** [comment]
I've just had a brief play.  It's easy to get DoB & NHS on one QR code using ASCII 09 to tab to the next field.  It's just one line to change in the QR generator function.  To avoid vandalising the files again I'll list the tweak here.

ps Our scanners are programmed to add a tab after every scan but I'll turn that off to avoid confusion.  

In functions.js update the QR code and delete the second code:

`text: formatDate(patient[keys['dob']]) + String.fromCharCode(09) + patient[keys['nhsno']] + String.fromCharCode(09) `

Also in funcoioni.js update the sticker layout to show on centred QR code, ie change to single cell row:

```
          <tr>
          <td><div class="qr-code" id="dob-qr-` + index + `"></div></td>
          </tr>
```

**Comment by Richard1793** [comment]
I think I've correctly created a new pull  request!  The only change is to function.js file.

**Comment by DrMikeyS** [comment]
Thanks @Richard1793 all implemented
