### ISSUE TITLE
Why letter layout?

### ISSUE THREAD

**Issue by Richard1793** [DrMikeyS/COVIDVaccinePatientSlips#19]
Out of interest is there a reason why the layout is letter size?

I left the surgery early today and thought I'd log in from home, create the sheets and email tomorrow's  PDF to be printed by someone in the surgery. Despite trying "print actual size" and other scale options on the PDF print options they couldn't get it to fit the labels.  I wonder if it was the A4/letter thing causing problems?

**Comment by DrMikeyS** [comment]
The letter format is an error I made early on that we are now stuck with. While trying to figure out the best way to get the stickers to fit the labels I was experimenting and left it on the US letter format. It wasn't needed and that is why the bottom row of labels are blank. I can change it easily, but people have got used to letter, so if I change it, people will get confused and annoyed. Any suggestions of how to go back to A4 gracefully will be gratefully received!
