### ISSUE TITLE
Date Print Error

### ISSUE THREAD

**Issue by JonThew** [DrMikeyS/COVIDVaccinePatientSlips#22]
I am having a problem that the print is coming out turning February in to March on the printed version. The QR code matches the print.
But I have checked the CSV files and the data is correctly showing February /02/ value but printing March /03/

**Comment by DrMikeyS** [comment]
This little bug keeps finding it's way back! I have pushed out the fix. Re-download and you should be good. Sorry for the inconvenience @JonThew and thanks for pointing it out

**Comment by JonThew** [comment]
@DrMikeyS thank you for the super fast response

quick query - any chance of the software reading the column in the Accubok Clinic export that says 'First/Second' instead of the date structure you show on the page where you suggest file structure?
