### ISSUE TITLE
Change second dose labels to allow first or second dose

### ISSUE THREAD

**Issue by Richard1793** [DrMikeyS/COVIDVaccinePatientSlips#25]
How about changing the mini labels to show "First Dose", "Second Dose", or no dose.

The reason is that we've ended up with 3 different batches (couldn't use all of each batch in care homes and home visits).  Plus we have a mix of 1st/2nds in our clinics.

So when we have to mop up odds and ends it'd be easier to print QR stickers without the batch number and  the actual batch can be added at the vaccination station.  It's probably only 2 or 3 vials each time but saves scribbling... or attempting to print QR stickers for all permutations.

**Comment by DrMikeyS** [comment]
As discussed in other thread, the target for this enhancement is to highlight the dose the patient is attending for regardless of first vs. second

**Comment by DrMikeyS** [comment]
Actioned in the dev release
