### ISSUE TITLE
Age labels for az only 

### ISSUE THREAD

**Issue by DrMikeyS** [DrMikeyS/COVIDVaccinePatientSlips#40]

**Comment by Richard1793** [comment]
Hi Mike

Your v2 doesn't work for me for some reason. I haven't time to dig into why. However, I've fixed the age under 30 for AZ in an older version. Just drop in this code after the under 18 check.

The check is for under 30 first then AZ. There won't be many under 30 so it should a bit quicker that way round

    if(age < 30) {
        if (vaccineType="AstraZeneca") {
            ageHTML = '<p class="under-30">This patient is under 30</p>'

I've also use the following css:

.stickers .under-18 {
font-size: 0.9rem;
font-weight: bold;
margin-bottom: 0;
background-color: violet;

}

.stickers .under-30 {
font-size: 0.9rem;
font-weight: bold;
margin-bottom: 0;
background-color: violet;

}

**Comment by Richard1793** [comment]
Tweaked the code:

**Comment by Richard1793** [comment]
Tweaked the code:

        // Check age limits
        age = getAge(patient[keys['dob']]);
        ageHTML = ""
        if (age < 30  && vaccineType=="AstraZeneca") {
                ageHTML = '<p class="under-30">This patient is under 30</p>'    
        } else if (age < 18) {
            ageHTML = '<p class="alert">This patient is under 18</p>'
        }

**Comment by DrMikeyS** [comment]
Thanks! I have committed this change (and a few extras) to the latest v2 release.
