### ISSUE TITLE
Patients with DOB in February are showing as March on QR labels

### ISSUE THREAD

**Issue by JoshLimeTree** [DrMikeyS/COVIDVaccinePatientSlips#41]
We have been using version 2.0 beta with a single QR code and have found when printing the labels if the patient date of birth is in February from the AccuRx data this then converts the date to March when printing labels.

Thanks,

Josh

**Comment by DrMikeyS** [comment]
Hi Josh,

I have just tried with version: https://github.com/DrMikeyS/COVIDVaccinePatientSlips/releases/tag/2.0b

I changed the DOB for the first dummy patient in the default CSV pack to 29/Feb/2020 and the date worked fine. Can you be more specific so I can debug?

Mike

**Comment by JoshLimeTree** [comment]
Hi Mike,

Thanks for the quick reply.

We have also downloaded version 2.0b and are using the latest version of Google Chrome.

I have set the first dummy patient to 21/02/2010 in the CSV, but this is how the labels generate before printing, see below:

***@***.***D73CF3.A8A42C50]

***@***.***D73CF3.A8A42C50]

Thanks,

Josh

**Comment by DrMikeyS** [comment]
When you say this is how they generate, what exactly do you mean? Do you get that string of text rather than the QR code?

Can you try the latest release (2.1)? In that dummy file "Hassan Riddle" has DOB  29-Feb-2020. For me this is working fine. Would be good to know if same for you.

**Comment by JoshLimeTree** [comment]
Hi Mike,

I have downloaded 2.1 and this is now working correctly for us.

Thank you,

Josh

**Comment by JoshLimeTree** [comment]
Hi Mike,

To confirm the dummy patient CSV generates the correct labels if the patient has a DOB in February however I have just loaded our afternoon AZ clinic into the generator which an export of data directly from AccuRx and all patients with a DOB in February are getting labels generated with the DOB set as March.

KR,

Josh

**Comment by DrMikeyS** [comment]
Fantastic
