### ISSUE TITLE
Feb dob changes to march in bar cod

### ISSUE THREAD

**Issue by DrDanH** [DrMikeyS/COVIDVaccinePatientSlips#42]
Thank you so much for this amazing piece of software. One issue that has just cropped up is that my Feb dates of birth are being changed to march! Is there a way I can sort this please?
many many thanks
dan

**Comment by DrMikeyS** [comment]
Hi Dan,

Can you double check the Accubook CSV export. The code seems to work fine but this issue has arisen suddenly, so I wonder if it is an accubook change. Please let me know what you find.

**Comment by Richard1793** [comment]
We also had this error this weekend.  All Feb DoB changed to March.

**Comment by DrMikeyS** [comment]
Thanks. It should be fixed in 2.1.1
