### ISSUE TITLE
Inccorect DOB

### ISSUE THREAD

**Issue by 2021Josh** [DrMikeyS/COVIDVaccinePatientSlips#51]
Having run the list to generate stickers from two different laptops we are getting Febuarry birthdays turning into march birthdays. This seams to be occouring on multiple people not just one.

**Comment by DrMikeyS** [comment]
Thanks for spotting. I think a chrome update has changed how the javascript is interpreted as was working fine before!

I have issued a fix that resolves it. Version 3.1
