### ISSUE TITLE
Addition of Booster 'VaccineDose'

### ISSUE THREAD

**Issue by ABDRSaxonbury** [DrMikeyS/COVIDVaccinePatientSlips#53]
Dear Dr MikeyS
I know you have ceased to work on the QR label generator, but I have found it invaluable and thank you sincerely for generating this.  I am the clinical site lead for a vaccination site and would be really appreciative if you could add a 'Booster' option in addition to 'First' and 'Second' options for the 'VaccineDose' column on the label printouts.
Many thanks for all you've done,
Adam

**Comment by miketrebilcock** [comment]
Hey Adam

I've forked this repo, it's such as useful tool it would be a shame for it not be kept running and updated.  I've added the booster dose option in as requested here: https://github.com/tango-3/COVIDVaccinePatientSlips

Mike

**Comment by ABDRSaxonbury** [comment]
Dear Mike

Thanks ever so much for releasing this- it saves invaluable time having this really useful resource which has proved so efficient and time-saving throughout the vaccination process, for myself and our front of house staff, but particularly the vaccinators.  Thank you for being so innovative and smart!  I can't profess to understand what the phrase 'I've forked this repo' but it seems to have worked!

If anyone replies to you with trouble printing out (this version seems to produce larger QR label images within google chrome so does not adhere to the 18 per page unless you change size of print), I changed to 69% size and it seems to work fine.

With many thanks and kind regards

Adam

Dr Adam Bennion
GP Principal
[cid:5fad942c-83e9-4410-868b-fe85fff9049e]
________________________________

**Comment by miketrebilcock** [comment]
Adam, 

Just fixed and updated, the latest release 3.14 prints correctly.

https://github.com/tango-3/COVIDVaccinePatientSlips/releases/tag/3.14

Mike

**Comment by ABDRSaxonbury** [comment]
Thanks Mike
Very much appreciated once more.
Kind regards
Adam

Dr Adam Bennion
GP Principal
[cid:22fa20cc-67c6-4426-a42f-b9d100441471]
________________________________
