### ISSUE TITLE
Single QR code

### ISSUE THREAD

**Issue by DrMikeyS** [DrMikeyS/COVIDVaccinePatientSlips#6]

**Comment by DrMikeyS** [comment]
Sadly not possible with our QR scanners (that I can figure out)

**Comment by zeubs** [comment]
@DrMikeyS First, love the work, nicely done.
We used and try to improve but were on Gitlab, check out out fork for a single QR code with TAB.
In essence the workaround is to paste into powershell a command that simulates key presses.
You can put just DOB TAB NHSno but can also introduce more to automate most of the form filling.

**Comment by DrMikeyS** [comment]
What an awesome solution! I think probably best to keep it as a separate fork as it is a bit more advanced,  and possibly beyond the technical ability of most practices. However I’ll definitely put a prominent link in the readme.

What’s your background out of interest? Where are you based?

**Comment by SGMLS** [comment]
Trying to add as much automation into the Pinnacle process as possible. v2beta3 is testing the single QR code printed onto stickers including Vacc details which can be entered by user who generates the QR codes from Accubook export. https://youtu.be/18Ch_6xFHbo

**Comment by DrMikeyS** [comment]
I have reopened this as I have made a start at incorporating the powershell approach into the main code. Please consider contributing @zeubs @SGMLS
