### ISSUE TITLE
Second dose

### ISSUE THREAD

**Issue by DrMikeyS** [DrMikeyS/COVIDVaccinePatientSlips#8]

**Comment by Richard1793** [comment]
Hi Mike

Your v2 doesn't work for me for some reason.  I haven't time to dig into why. However, I've fixed the age under 30 for AZ in an older version.  Just drop in this code after the under 18 check.  

The check is for under 30 first then AZ.  There won't be many under 30 so it should a bit quicker that way round

        if(age < 30) {
            if (vaccineType="AstraZeneca") {
                ageHTML = '<p class="under-30">This patient is under 30</p>'

I've also use the following css:

            }
        }
